Repository Spordi/Pluginus1, pull requests merged in 2020-05, with the labels that each got.

#9 Sortierung
  src/plugin.yml
  src/wasdenn/Commands/GmCommand.java
  src/wasdenn/Commands/HealCommand.java
  src/wasdenn/Commands/InvCommand.java
  src/wasdenn/Commands/SdmCommand.java
  src/wasdenn/Commands/WahrheitCommand.java
  src/wasdenn/Listeners/ChatListener.java
  src/wasdenn/Listeners/JoinLeaveKickListener.java
  src/wasdenn/Main.java
Labels: enhancement

#10 Meyssam
  src/wasdenn/Commands/HealCommand.java
  src/wasdenn/Main.java
Labels: question

#11 Added /wartung
  src/plugin.yml
  src/wasdenn/Commands/Wartungsmodus.java
  src/wasdenn/Listeners/JoinLeaveKickListener.java
  src/wasdenn/Listeners/PingListener.java
  src/wasdenn/Main.java
Labels: enhancement

#23 BugFixes
  src/wasdenn/Listeners/InteractListener.java
  src/wasdenn/Listeners/InventoryListener.java
Labels: bug
